### ISSUE TITLE
Error when run "run_convert_DF.sh" for processing data

### ISSUE THREAD

**Issue by codaibk** [charliememory/Pose-Guided-Person-Image-Generation#10]
Hi. When i tried to process data with "run_convert_DF.sh" i get this error. Do you know how i can solve it?
Thanks
```
File "convert_DF.py", line 1005, in <module>
    run_one_pair_rec(dataset_dir, out_dir, split_name)
  File "convert_DF.py", line 982, in run_one_pair_rec
    mode='same_diff_cam')
  File "convert_DF.py", line 172, in _get_train_all_pn_pairs
    pickle.dump(p_pairs,f)
TypeError: write() argument must be str, not bytes
```

**Comment by rosdyana** [comment]
I guess you're using python3 instead of python2, I think it's better if @charliememory can provide the requirements list, such as python version, tensorflow version, etc.

**Comment by codaibk** [comment]
Thanks @rosdyana . You are right. my problem fixed after following your suggestion ^^
