### ISSUE TITLE
How to produce a test file？

### ISSUE THREAD

**Issue by ZhangYK124** [charliememory/Pose-Guided-Person-Image-Generation#12]
Now I want to test the code with other datasets,  
But I don't know how Market1501_test_00000-of-00001.tfrecord, n_pairs_test.p, p_pairs_test.p, pn_pairs_num_test.p are produced in the Market_test_data.zip folder.

**Comment by charliememory** [comment]
You can check the `datasets/run_convert_market.sh` and `datasets/convert_market.py`. BTW, here we use the pose estimation results from https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation  . So we need to obtain the final key-points coordinates results from peaks and subsets with some functions provided in `datasets/convert_market.py`. We will also provide more convenient scripts to use the key-points coordinates from OpenPose directly.

**Comment by MTonyM** [comment]
Hi!
Could you tell me where is the so-called more convenient scripts in 
"We will also provide more convenient scripts to use the key-points coordinates from OpenPose directly."
Thanks. And **how to produce a custom test file?**

**Comment by charliememory** [comment]
Sorry for the inconvenience. The scripts are developed in another repo https://github.com/charliememory/Disentangled-Person-Image-Generation

Now, I upload the two files `convert_RCV.py` and `run_convert_RCV.sh` in the datasets directory.
Please check here to convert the Row-Column-Visibility form keypoints data.
https://github.com/charliememory/Pose-Guided-Person-Image-Generation/blob/d6122a319a6f4af845883933cc12ffc1da09cb19/datasets/convert_RCV.py#L593
