### ISSUE TITLE
Unable to find function for pose estimation

### ISSUE THREAD

**Issue by 314rated** [charliememory/Pose-Guided-Person-Image-Generation#2]
Hi,
I am unable to identify the function for pose estimation. I believe that the tf-records of test data already contain precomputed pose information (Correct me if that is not the case). Could you please direct me to the pose estimation and mask estimation function? 

Thanks

**Comment by charliememory** [comment]
We use https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation to obtain the pose keypoints and then store them in pickle files. You can find them 'all_peaks_dic_DeepFashion.p' and 'subsets_dic_DeepFashion.p' in the raw data zip.
As to the mask estimation function, you can find the  '_getPoseMask' function in datasets/convert_market.py and datasets/convert_DF.py
