### ISSUE TITLE
Datasets Cannot Be Downloaded - Error 403: Forbidden

### ISSUE THREAD

**Issue by smbadiwe** [charliememory/Pose-Guided-Person-Image-Generation#21]
Hi,

I could not access any of the datasets / trained models. The server is returning ERROR 403: Forbidden. Will you please fix the problem again? Thanks!

[I'm aware this has happened before and was addressed](https://github.com/charliememory/Pose-Guided-Person-Image-Generation/issues/14). The issue is back again.

**Comment by charliememory** [comment]
Fixed now.

**Comment by leonardishere** [comment]
Hi, it's 403 forbidden again. Can you please fix it again? Also, is there a mirror?
