### ISSUE TITLE
Pytorch implementation of "Pose Guided Person Image Generation"

### ISSUE THREAD

**Issue by budui** [charliememory/Pose-Guided-Person-Image-Generation#29]
@charliememory  Thanks for your patience. (￣▽￣)", I have implemented your paper with Pytorch.

Pytorch implemention: [Human-Pose-Transfer](https://github.com/budui/Human-Pose-Transfer)
result:

![image](https://user-images.githubusercontent.com/16448529/57969439-7d4ad180-79a9-11e9-9af5-de3f041d0471.png)

https://github.com/budui/Human-Pose-Transfer#implement-result
In addition, I also implemented `PatchGAN-PG2`, `LSLoss-PG2`

`target` `PG2` `LSLoss-PG2` `PatchGAN-PG2`
![image](https://user-images.githubusercontent.com/16448529/57969362-d9f9bc80-79a8-11e9-8b5c-949048aa5931.png)

**Comment by charliememory** [comment]
Thanks for your nice implementation.
