### ISSUE TITLE
Mismatch shape when loading pretrained model

### ISSUE THREAD

**Issue by AnqiYang** [charliememory/Pose-Guided-Person-Image-Generation#3]
When I load the pre-trained DeepFusion model, it encounters shape mismatch. 

Pretrained model: UAEnoFC/G/conv18: [3, 3, 256, 128]
current sesson graph: UAEnoFC/G/conv18: [3, 3, 128, 128]

Could you please clarify the graph definition in trainer.py?

**Comment by chunfenghuayumm** [comment]
Did u fix this out?

**Comment by charliememory** [comment]
Sorry for the late update. Bugs in the testing code are fixed now.
