### ISSUE TITLE
The target pose generation

### ISSUE THREAD

**Issue by hunterchenghx** [charliememory/Pose-Guided-Person-Image-Generation#30]
You said you used a pose estimator to generate the target pose and transformed them into 18 heatmaps. Is that procedure included in this code? Or the dataset you offered already contains the target pose?

**Comment by charliememory** [comment]
Yes, the procedure is included and the dataset contains the target pose. While the estimated pose data structure is complex because it is based on old Openpose code. The new Openpose can output the coordinates of the 18 keypoints directly.

**Comment by chq1996** [comment]
sorry ,excuse me, i  have no access to the pretrained model,  can you send it to me, my email is chq1996@hhu.edu.cn.
thank you

**Comment by charliememory** [comment]
> sorry ,excuse me, i have no access to the pretrained model, can you send it to me, my email is [chq1996@hhu.edu.cn](mailto:chq1996@hhu.edu.cn).
> thank you

The links are fixed now.

**Comment by chq1996** [comment]
ok，thanks
