### ISSUE TITLE
Question of some codes in trainer.py

### ISSUE THREAD

**Issue by longintlong** [charliememory/Pose-Guided-Person-Image-Generation#32]
Hi! Thanks for your open-source code of your project. I have few questions about some details in trainer.py.
Why do you  cycle 400 times in the test procedure?
Is every iteration better than the previous one?
Thanks a lot!

**Comment by charliememory** [comment]
The test loop is applied to process the test data batch-by-batch. In each batch, we just process a small number of data.

**Comment by longintlong** [comment]
> The test loop is applied to process the test data batch-by-batch. In each batch, we just process a small number of data.

Thanks~

**Comment by longintlong** [comment]
Hi!  I have another question about convert code on market data.
In convert market data code, there are other files in convert deepfashion data  code  does not have, for example the  attr_onehot_mat and attr_w2v_dir..
 What are the functions of these files?
What happens if there are no such files?

**Comment by charliememory** [comment]
These files are just provided for extra information, but not used for the current person generation models.
