### ISSUE TITLE
use of pretrained models

### ISSUE THREAD

**Issue by Seairis7** [charliememory/Pose-Guided-Person-Image-Generation#35]
How to use pretrained model for single image pose change

**Comment by Seairis7** [comment]
How to use pretrained model for single image conversion

**Comment by charliememory** [comment]
Hi, I didn't implement the API for single image testing. You can either transform the image into the tf-record (please check comments at https://github.com/charliememory/Pose-Guided-Person-Image-Generation/issues/34#issuecomment-545394949) or implement the single image testing API.
