### ISSUE TITLE
Some details of net architecture

### ISSUE THREAD

**Issue by vicmax** [charliememory/Pose-Guided-Person-Image-Generation#4]
Hi, Liqian,
Thanks for your open-source code of your project. I have few questions about some details in your network:
Q1: In [1]:
I note that in the decoders of G1 and G2, you use `upscale + conv` to up-sample the feature map, and you comment a line in which `transposed conv` is used to up-sample. These two methods, do they have big influence on the final performance?
[Just see code here](https://github.com/charliememory/Pose-Guided-Person-Image-Generation/blob/master/models.py#L144)

Q2:Based on Q1, which of method you used in your paper [2]?

Q3: In [2]:
In Sec 3.4, what the expressions `"fully-connected residual layers"` mean? 
![1](https://user-images.githubusercontent.com/30364036/39191484-9dd9e1ca-4809-11e8-9f39-9e4df3de6268.jpg)
Because your illustrations in supplementary materials looks that the `"mapping functions"` and `"Pose auto-encoder"` just consists of simple fully-connections. I haven't found any `"residual"` elements.
![2](https://user-images.githubusercontent.com/30364036/39191516-aa1ccefc-4809-11e8-939c-27d00801e512.jpg)
![3](https://user-images.githubusercontent.com/30364036/39191525-b0c32990-4809-11e8-8a04-1180ef14e7a9.jpg)

Looking forward to your reply.

References:
[1]Ma, L., Jia, X., Sun, Q., Schiele, B., Tuytelaars, T., & Van Gool, L.. Pose Guided Person Image Generation. NIPS2017
[2]Disentangled Person Image Generation

**Comment by charliememory** [comment]
Thanks for your interests in our work.
1) The results of using `upscale + conv` and `transposed conv` are similar.
2) The `upscale + conv` is used in the paper [2].
3) The "fully-connected residual layers" contain two fully-connected layer in each residual block,  look like this
```
def PoseEncoderFCRes(pose_rcv, z_num, repeat_num, hidden_num, data_format, activation_fn=tf.nn.elu, reuse=False):
    with tf.variable_scope("G_Pose_Encoder",reuse=reuse) as vs:
        ## Encoder
        x = slim.fully_connected(pose_rcv, hidden_num, activation_fn=activation_fn)
        for i in range(repeat_num):
            res = x
            x = slim.fully_connected(x, hidden_num, activation_fn=activation_fn)
            x = slim.fully_connected(x, hidden_num, activation_fn=activation_fn)
            x = res + x
        out = slim.fully_connected(x, z_num, activation_fn=None)
    variables = tf.contrib.framework.get_variables(vs)
    return out, variables
```

**Comment by vicmax** [comment]
@charliememory Thanks for your reply! And please forgive me for my further questions:

Q4: In [2], what's the detailed architecture to get preliminary feature map in Stage-1(the red rectangle)? 
![screenshot from 2018-04-28 18-01-26](https://user-images.githubusercontent.com/30364036/39395291-6362118a-4b0f-11e8-9533-42e2f888ec44.png)

Q5: When will you update your code of [Disentangled-Person-Image-Generation](https://github.com/charliememory/Disentangled-Person-Image-Generation)? Looking forward to that.

**Comment by charliememory** [comment]
@vicmax 
4. The architecture is just one conv layer with a residual block as follows,
```
# Encoder
x = slim.conv2d(x, hidden_num, 3, 1, activation_fn=activation_fn, data_format=data_format)
res = x
x = slim.conv2d(x, hidden_num, 3, 1, activation_fn=activation_fn, data_format=data_format)
x = slim.conv2d(x, hidden_num, 3, 1, activation_fn=activation_fn, data_format=data_format)
x = x + res
```
5. We plan to update that project in May.

**Comment by vicmax** [comment]
@charliememory Thanks~  And happy Workers' Day!
