### ISSUE TITLE
AttributeError: 'PG2_256' object has no attribute 'G'

### ISSUE THREAD

**Issue by bandontseng** [charliememory/Pose-Guided-Person-Image-Generation#5]
There is an error when I run run_DF_test.sh.

AttributeError: 'PG2_256' object has no attribute 'G'

I think we have to assign self.G as self.G2 in the build_model model of PG2_256 in trainer256.py:

        self.G1 = denorm_img(G1, self.data_format)
        self.G2 = denorm_img(G2, self.data_format)
        self.G = self.G2   # Add this to fix no attribute 'G' error

**Comment by charliememory** [comment]
Indeed, it is fixed now. Thanks for your feedback.
